<Label>
    font_name: 'uasquare'
    font_size: '14sp'
    halign: 'right'
    
<Button>
    font_name: 'uasquare'
    font_size: '14sp'
    halign: 'center'
    # background_normal: 'atlas://textures/sprites/button'
    # background_down: 'atlas://textures/sprites/button_down'
    #border: 5,5,5,5

<TextInput>
    font_name: 'uasquare'
    font_size: '14sp'
    background_color: [0.0,0.0,0.0,1.0]
    foreground_color: [1.0,1.0,0.0,1.0]
    height: 50
